### PR TITLE
Fix missing include

### PR DESCRIPTION
**Pull request by traversaro**
Should fix compilation error introduced in https://github.com/robotology/wholebodyinterface/commit/df125b05c2836c8c8d440e9577af0a98905bfa8b .

### CODE REVIEW

**Comment by traversaro** [comment]
Merging because otherwise all the tests involving the superbuild continue to fail : https://travis-ci.org/robotology/wholebodyinterface/builds/145226149 .
